---
name: "master release"

on:
  push:
    paths:
      - 'config/**'
    branches:
      - "master"

  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    needs: build
    steps:
      - uses: actions/download-artifact@master
        with:
          name: firmware
          path: build/artifacts

      - name: Updating Git release tag with Development Build
        uses: "softprops/action-gh-release@v2"
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "Development Build"
          name: "Latest development release"
          prerelease: true
          generate_release_notes: true
          files: |
            build/artifacts/*.uf2
