---
name: "tag release"

on:
  push:
    paths:
      - 'config/**'
    tags:
      - '*'

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: firmware
          path: build/artifacts

      - name: Updating Git release tag with Development Build
        uses: "softprops/action-gh-release@v2"
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          generate_release_notes: true
          files: |
            build/artifacts/*.uf2
